# Clase 2 - Analisis de Datos

## Libraries

----

We import the libraries to use

In [53]:
import pandas as pd
import numpy
import re
import math

## Absolute and relative paths

---

Python scripts are executed in a shell. Said shells have an active directory (in our case, the folder NEW_3RD_SEMESTER), which is nothing more than the folder we are working on. If we want to open a file through shell commands (or python scripts that execute shell commands) we need to specify the **path** of the file. To do so we have two options: (1) Use an **absolute path** or (2) use a **realtive path**.

### What is an absolute path?

An **absolute path** is nothing more than the full tree-like path of the file, starting from the storage unit that contains it, an example of such a path is `C:/Users/ossia/Documents/SEMESTRES_FACULTAD/New_3rd_semester/INPUTS/INE_ENTIDAD_2020.csv`. 

### What is a relative path?

A  **relative path** relies on the the active/working directory of the shell through which we execute the code. If the file we want is inside the active folder, then only the name of the file along with its extension is necessary. If the file is not, then we need to give its relative path, i.e. its path starting from the point of view of the working directory. To move thorough folders we can use shell commands such as `../` or `/INPUTS/`. The former specifies that the file in the parent directory of our current folder, the latter that the file is in a child directory (a nested folder inside our active one). After each of this commands, we place the name and the extension of the file in question; an example would be `../INPUTS/INE_ENTIDAD_2020.CSV`.

### Which is best?

Which is best will depend on the context, although most of the time using relative paths will prove to be the most optimal. To ensure such optimality, specific data storage frameworks are developed. We, for example, defined 3 folders in the parent directory for the class:

- INPUTS
- OUTPUTS
- SCRIPTS

This way we mantain our files organized and we have an easy way of identifying where a file can be.

## Reading data with pandas

---

To read a comma-separated file using pandas we use the function `pd.read_csv(path, encoding, ...)`. The information will be stored in a python object called a **dataframe** (panda's propietary data type). As such, for the object to be stored in memory, a name must be assigned to it. 

In the next block of code we read the file INE_ENTIDAD_2020.csv by using its relative and absolute path. As a note, observe that by placing the name of the object `df` in a new line, a colapsed version of the dataframe is printed (this is a perk only ipython and other REPL shells).

In [54]:
df = pd.read_csv("C:/Users/ossia/Documents/SEMESTRES_FACULTAD/New_3rd_semester/INPUTS/INE_ENTIDAD_2020.csv", encoding = "latin-1")    # Absolute path - Como hay acentos y ñs, se cambia el encoding a latin-1
df = pd.read_csv("../INPUTS/INE_ENTIDAD_2020.CSV", encoding = "latin-1")    # Relative path
df

,ENT,NOM_ENT,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,P_0A2_M,P_0A17,P_3YMAS,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCIN,VPH_SINTIC
0,1,Aguascalientes,1425607,728924,696683,71864,35604,36260,463335,1352235,...,147818,359895,236003,174089,98724,70126,6021,15323,128996,1711
1,2,Baja California,3769020,1868431,1900589,149957,74010,75947,1061893,3610844,...,576806,1080169,800189,618175,384011,216865,41223,38772,293529,9582
2,3,Baja California Sur,798447,392568,405879,35963,17821,18142,236629,758642,...,91750,226517,148723,136538,67961,36197,14508,8675,77223,2608
3,4,Campeche,928363,471424,456939,45541,22506,23035,286880,878528,...,68843,218322,114020,151613,38508,17976,23627,36397,130361,12028
4,5,Coahuila de Zaragoza,3146771,1583102,1563669,160368,79095,81273,982841,2980244,...,372132,824291,519599,443659,195883,124077,17020,46420,332298,5754
5,6,Colima,731391,370769,360622,29614,14483,15131,209402,699821,...,80251,206736,132395,114164,43881,22695,9173,12085,82366,2698
6,7,Chiapas,5543828,2837881,2705947,334055,165892,168163,2093426,5181929,...,159652,944695,292189,433400,61298,32460,214333,379915,993929,151655
7,8,Chihuahua,3741869,1888047,1853822,163950,80466,83484,1137537,3570280,...,460540,1051045,650546,481871,282049,179964,42113,64419,432032,20158
8,9,Ciudad de México,9209944,4805017,4404927,267151,131720,135431,2033581,8933167,...,1898265,2536523,2084156,1290811,957162,568827,46172,77272,561128,10528
9,10,Durango,1832650,927784,904866,95793,47204,48589,612346,1733682,...,137873,434450,215108,222785,73099,54664,22071,41801,243750,12446
10,11,Guanajuato,6166934,3170480,2996454,313928,154709,159219,1965943,5840957,...,529217,1381668,764350,681879,240833,167748,46126,134421,732192,20559
11,12,Guerrero,3540685,1840073,1700612,197506,97545,99961,1237843,3328762,...,252529,715753,298180,343146,56999,28577,125684,172608,599093,70622
12,13,Hidalgo,3082841,1601462,1481379,134738,66770,67968,958875,2944897,...,210637,727888,332320,378326,95701,64475,51691,102005,467376,26079
13,14,Jalisco,8348151,4249696,4098455,384145,190072,194073,2531145,7912955,...,1009963,2134429,1437473,1199700,573528,375678,56399,96948,760439,17553
14,15,México,16992418,8741123,8251295,724133,357766,366367,5009259,16260058,...,2123211,4049493,2561525,1559564,822048,572663,133777,329132,1769551,53857
15,16,Michoacán de Ocampo,4748846,2442505,2306341,251800,124627,127173,1544594,4493516,...,333332,1123169,561753,684146,149704,101530,57579,111766,655580,23842
16,17,Morelos,1971520,1020673,950847,82809,40825,41984,568743,1887763,...,236487,499787,307830,222853,90825,48209,24696,34950,227132,7724
17,18,Nayarit,1235456,623178,612278,59549,29305,30244,394457,1174739,...,108011,318700,169289,178574,60325,35983,20501,28481,167969,9171
18,19,Nuevo León,5784442,2893492,2890950,258166,127997,130169,1654929,5508144,...,922162,1537687,1150914,806584,490746,306104,36729,57505,439479,9797
19,20,Oaxaca,4132148,2157305,1974843,205460,101721,103739,1372915,3917300,...,223680,812319,329811,321144,60715,29789,181771,263541,736533,106502
20,21,Puebla,6583278,3423163,3160115,339025,167898,171127,2148335,6238582,...,490546,1444126,691363,539920,213909,129993,102541,207818,939937,49800
21,22,Querétaro,2368467,1211647,1156820,108229,53878,54351,700525,2253414,...,289497,606978,430045,382086,183742,106431,22702,44358,208004,9228
22,23,Quintana Roo,1857985,921206,936779,84393,41380,43013,543728,1752570,...,158739,526202,319194,267556,131827,55902,43642,36378,221620,12239
23,24,San Luis Potosí,2822255,1449804,1372451,132634,65809,66825,879923,2687679,...,267599,653195,344443,347311,128861,83293,43489,90622,388169,23153
24,25,Sinaloa,3026943,1532128,1494815,139403,68525,70878,902580,2885315,...,210473,787350,441062,457908,162367,92477,35425,50477,365642,12648
25,26,Sonora,2944840,1472643,1472197,124294,61239,63055,876174,2817821,...,244972,811378,530511,501521,210780,126299,32807,48777,302080,11895
26,27,Tabasco,2402598,1228927,1173671,118339,58414,59925,781519,2283383,...,118527,563390,228487,276817,66338,31004,54983,96508,404524,25731
27,28,Tamaulipas,3527735,1791595,1736140,154958,76445,78513,1046920,3367123,...,413157,985027,580241,434549,197140,116590,39790,55012,436801,11760
28,29,Tlaxcala,1342977,693083,649894,63959,31786,32173,421140,1258093,...,97434,289686,131845,124796,27291,18744,11774,34553,183348,5272
29,30,Veracruz de Ignacio de la Llave,8062579,4190805,3871774,342746,169702,173044,2378935,7716363,...,635994,1971776,959542,914961,268958,133977,183055,342920,1329356,94369
30,31,Yucatán,2320898,1180619,1140279,101151,49841,51310,666922,2215931,...,176401,580440,339142,306523,129272,60161,33887,67719,283586,16519
31,32,Zacatecas,1622138,831080,791058,88433,43820,44613,544684,1531847,...,138052,372814,204945,214337,51656,37622,13243,43316,214181,5383

### About encoding

Note that there is a 2nd argument in the functions used to read the csv, that of '*encoding = 'latin-1*'. Since we are using spanish, and hence need to use the letter 'ñ', it is important to specify the encoding such that said symbol is read correctly. We used the encoding **latin-1**; by default the encoding used is **UTF-8**.

##  Understanding Pandas' data structures

---

The pandas library introduces several new data structures to python; the main ones are `Series` and `Dataframe`, with `Index object` being another one that's often ommited at a first glance.   

### Pandas Series

---

##### **What is a Series?** 

A Series is a one-dimenisonal array-like object containing a **sequence of values** of the same type **and an associated array of data labels**, called its **index**. We can think of Serias as fixed length, ordered dictionaries (for they are essentially mapping the index values to the data values).

PENDIENTE - COMPLETAR APUNTES: LO BASICO DE PD.SERIES When defining a Series object, by default its index consists of the integers from 0 to N-1.

Important remarks about Series:

- Default index is the range(0,N)
- The index can be altered in place by assignment
- They have data anlignment features (useful when doing operations)
- Mutable
- Have a name attribute
- You can use the labels to select single or sets of values
- The index-value link is preserved under operations
- Can be parsed back and forth from a python dictionary

### Pandas DataFrame

---

A DataFrame is a **rectangular table of data** that contains an **ordered and named collection of columns**, each of which can be of a different data type. Simmilarly to Series, **it has both a row and column index**. Again, simmilarly to Series, a DataFrame can be though of as a dictionary of Series that share the same index.

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Columns: 222 entries, ENT to VPH_SINTIC
dtypes: float64(7), int64(214), object(1)
memory usage: 55.6+ KB

### Column retrieval

Por que da un error al intentar seleccionar la columna "NOM_ENT"? Analizando el dataframe, podemos ver que hay una fila con ese nombre. Donde esta el problema?

In [57]:
df["NOM_ENT"]

KeyError: 'NOM_ENT'

In [56]:
df.columns

Index(['ENT', 'NOM_ENT ', 'POBTOT', 'POBFEM', 'POBMAS', 'P_0A2', 'P_0A2_F',
       'P_0A2_M', 'P_0A17', 'P_3YMAS',
       ...
       'VPH_TELEF', 'VPH_CEL', 'VPH_INTER', 'VPH_STVP', 'VPH_SPMVPI',
       'VPH_CVJ', 'VPH_SINRTV', 'VPH_SINLTC', 'VPH_SINCIN', 'VPH_SINTIC'],
      dtype='object', length=222)

Analizando los nombres de las columnas, se puede observar que la columna NOM_ENT tiene un espacio extra al final. Es por eso que al llamarla usando el string "NOM_ENT" ocurre un error. Para obtener la columna entonces necesitamos especificar "NOM_ENT ".

### Basic DataFrame exploration and filtering

- Column retrieval (dictornary style or dot attribute)
- .info
- .head
- .tail
- .columns
    - .strip
- Row retrieval
    - .iloc
    - .loc

In [58]:
df[df["NOM_ENT "] != "Nuevo León"]

,ENT,NOM_ENT,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,P_0A2_M,P_0A17,P_3YMAS,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCIN,VPH_SINTIC
0,1,Aguascalientes,1425607,728924,696683,71864,35604,36260,463335,1352235,...,147818,359895,236003,174089,98724,70126,6021,15323,128996,1711
1,2,Baja California,3769020,1868431,1900589,149957,74010,75947,1061893,3610844,...,576806,1080169,800189,618175,384011,216865,41223,38772,293529,9582
2,3,Baja California Sur,798447,392568,405879,35963,17821,18142,236629,758642,...,91750,226517,148723,136538,67961,36197,14508,8675,77223,2608
3,4,Campeche,928363,471424,456939,45541,22506,23035,286880,878528,...,68843,218322,114020,151613,38508,17976,23627,36397,130361,12028
4,5,Coahuila de Zaragoza,3146771,1583102,1563669,160368,79095,81273,982841,2980244,...,372132,824291,519599,443659,195883,124077,17020,46420,332298,5754
5,6,Colima,731391,370769,360622,29614,14483,15131,209402,699821,...,80251,206736,132395,114164,43881,22695,9173,12085,82366,2698
6,7,Chiapas,5543828,2837881,2705947,334055,165892,168163,2093426,5181929,...,159652,944695,292189,433400,61298,32460,214333,379915,993929,151655
7,8,Chihuahua,3741869,1888047,1853822,163950,80466,83484,1137537,3570280,...,460540,1051045,650546,481871,282049,179964,42113,64419,432032,20158
8,9,Ciudad de México,9209944,4805017,4404927,267151,131720,135431,2033581,8933167,...,1898265,2536523,2084156,1290811,957162,568827,46172,77272,561128,10528
9,10,Durango,1832650,927784,904866,95793,47204,48589,612346,1733682,...,137873,434450,215108,222785,73099,54664,22071,41801,243750,12446
10,11,Guanajuato,6166934,3170480,2996454,313928,154709,159219,1965943,5840957,...,529217,1381668,764350,681879,240833,167748,46126,134421,732192,20559
11,12,Guerrero,3540685,1840073,1700612,197506,97545,99961,1237843,3328762,...,252529,715753,298180,343146,56999,28577,125684,172608,599093,70622
12,13,Hidalgo,3082841,1601462,1481379,134738,66770,67968,958875,2944897,...,210637,727888,332320,378326,95701,64475,51691,102005,467376,26079
13,14,Jalisco,8348151,4249696,4098455,384145,190072,194073,2531145,7912955,...,1009963,2134429,1437473,1199700,573528,375678,56399,96948,760439,17553
14,15,México,16992418,8741123,8251295,724133,357766,366367,5009259,16260058,...,2123211,4049493,2561525,1559564,822048,572663,133777,329132,1769551,53857
15,16,Michoacán de Ocampo,4748846,2442505,2306341,251800,124627,127173,1544594,4493516,...,333332,1123169,561753,684146,149704,101530,57579,111766,655580,23842
16,17,Morelos,1971520,1020673,950847,82809,40825,41984,568743,1887763,...,236487,499787,307830,222853,90825,48209,24696,34950,227132,7724
17,18,Nayarit,1235456,623178,612278,59549,29305,30244,394457,1174739,...,108011,318700,169289,178574,60325,35983,20501,28481,167969,9171
19,20,Oaxaca,4132148,2157305,1974843,205460,101721,103739,1372915,3917300,...,223680,812319,329811,321144,60715,29789,181771,263541,736533,106502
20,21,Puebla,6583278,3423163,3160115,339025,167898,171127,2148335,6238582,...,490546,1444126,691363,539920,213909,129993,102541,207818,939937,49800
21,22,Querétaro,2368467,1211647,1156820,108229,53878,54351,700525,2253414,...,289497,606978,430045,382086,183742,106431,22702,44358,208004,9228
22,23,Quintana Roo,1857985,921206,936779,84393,41380,43013,543728,1752570,...,158739,526202,319194,267556,131827,55902,43642,36378,221620,12239
23,24,San Luis Potosí,2822255,1449804,1372451,132634,65809,66825,879923,2687679,...,267599,653195,344443,347311,128861,83293,43489,90622,388169,23153
24,25,Sinaloa,3026943,1532128,1494815,139403,68525,70878,902580,2885315,...,210473,787350,441062,457908,162367,92477,35425,50477,365642,12648
25,26,Sonora,2944840,1472643,1472197,124294,61239,63055,876174,2817821,...,244972,811378,530511,501521,210780,126299,32807,48777,302080,11895
26,27,Tabasco,2402598,1228927,1173671,118339,58414,59925,781519,2283383,...,118527,563390,228487,276817,66338,31004,54983,96508,404524,25731
27,28,Tamaulipas,3527735,1791595,1736140,154958,76445,78513,1046920,3367123,...,413157,985027,580241,434549,197140,116590,39790,55012,436801,11760
28,29,Tlaxcala,1342977,693083,649894,63959,31786,32173,421140,1258093,...,97434,289686,131845,124796,27291,18744,11774,34553,183348,5272
29,30,Veracruz de Ignacio de la Llave,8062579,4190805,3871774,342746,169702,173044,2378935,7716363,...,635994,1971776,959542,914961,268958,133977,183055,342920,1329356,94369
30,31,Yucatán,2320898,1180619,1140279,101151,49841,51310,666922,2215931,...,176401,580440,339142,306523,129272,60161,33887,67719,283586,16519
31,32,Zacatecas,1622138,831080,791058,88433,43820,44613,544684,1531847,...,138052,372814,204945,214337,51656,37622,13243,43316,214181,5383

## Ejercicios

---

### Ejercicio 0

Traer los nombre de los estados y la poblacion total del DataFrame

### Ejercicio 1

Traer los nombres y poblacion total de Aguascalientes y Nuevo Leon.

Solucion 1:

In [59]:
df.loc[(df["NOM_ENT "] == "Nuevo León") | (df["NOM_ENT "] == "Aguascalientes"), ["NOM_ENT ", "POBTOT"]] # No tan legible

          NOM_ENT    POBTOT
0   Aguascalientes  1425607
18      Nuevo León  5784442

Solucion 2:

In [60]:
df.loc[:, ["NOM_ENT ", "POBTOT"]][(df["NOM_ENT "] == "Nuevo León") | (df["NOM_ENT "] == "Aguascalientes")] # El menos optimo

          NOM_ENT    POBTOT
0   Aguascalientes  1425607
18      Nuevo León  5784442

Solucion 3:

In [61]:
df.loc[df["NOM_ENT "].isin(["Aguascalientes", "Nuevo León"]), ["NOM_ENT ", "POBTOT"]] # La mejor solucion de las tres

          NOM_ENT    POBTOT
0   Aguascalientes  1425607
18      Nuevo León  5784442

In [62]:
# Para quitar el espacio en blanco del nombre de la columna "NOM_ENT " hacemos:

df.columns = df.columns.str.strip()

# Efectivamente quitando los espacios extras a la izquierda y derecha de todos los nombres de las columnas

### Ejercicio 2

Traer nombre de la entidad, poblacion masculina y poblacion femenina del estado con mayor poblacion total.

In [63]:
max_pob = int(df['POBTOT'].max())

df.loc[df["POBTOT"] == df['POBTOT'].max(), ["NOM_ENT", "POBMAS", "POBFEM"]].head(1)

   NOM_ENT   POBMAS   POBFEM
14  México  8251295  8741123

### Ejercicio 3

Traer nombre de la entidad, poblacion masculina y poblacion femenina del estado con menor poblacion total

In [64]:
# Ejercicio 3: Traer nombre de la entidad, poblacion masculina y poblacion femenina del estado con menor poblacion total

df.loc[df["POBTOT"] == df['POBTOT'].min(), ["NOM_ENT", "POBMAS", "POBFEM"]].head(1)

  NOM_ENT  POBMAS  POBFEM
5  Colima  360622  370769

### Key IDs

---

Cuandro trabajamos con bases de datos (especialmente bases de datos relacionales) cada fila contiene una serie de valores para un mismo objeto. La identidad de dicho objeto siempre esta relacionada con un ID llave, el cual es unico. Este ID suele ser un tipo de dato mas simple, eficientizando las llamadas a los datos, y facilitando la relacion entre distintas tablas de datos dentro de la base de datos.

Dicho ID llave suele respetar el formato que se tiene para los demas datos de la tabla (mayus o minus dependiendo de los demas datos). El estandar es que sea tipo caracter.

Para esta base datos, ENT es nuestro key ID.

Lo primero que hacemos es verificar que tipo de dato tiene la Series asociada a la columna de "ENT" que en nuestro Key ID.

In [ ]:
# Verificamos el tipo de dato de df["ENT"]
print(type(df["ENT"][0]))

<class 'numpy.int64'>

Como es tipo int64, tenemos que hacer casting a string. Eso se hace la siguiente manera:

In [ ]:
# df.loc[:, "ENT"] = df["ENT"].astype(str) # Esto ya no sirve en la version mas actual de pandas para python 3.14 POR QUE YA NO FUNCIONA? PENDIENTE

df["ENT"] = df["ENT"].astype(str) # Esto sirve para python 3.14 - ESTO ES UNA MEJOR OPCION 

print(type(df["ENT"][0]))

<class 'str'>

## Tarea clase 02

---

### Ejercicio tarea 1

Traer nombre de la entidad, poblacion total, poblacion masculina y poblacion femenina del estado con menor poblacion femenina y el estado con mayor poblacion masculina

In [65]:
df.loc[(df["POBFEM"] == df['POBFEM'].min()) | (df["POBMAS"] == df['POBMAS'].max()), ["NOM_ENT", "POBTOT", "POBMAS", "POBFEM"]]

   NOM_ENT    POBTOT   POBMAS   POBFEM
5   Colima    731391   360622   370769
14  México  16992418  8251295  8741123

### Ejercicio tarea 2

Que estados tienen poblacion masculina menor o igual al promedio de poblacion femenina y cual es su poblacion total?

In [66]:
mean_pobfem = numpy.mean(df["POBFEM"])
print("El promedio de poblacion femenina es de ", mean_pobfem)
df.loc[(df["POBMAS"] <= mean_pobfem), ["NOM_ENT", "POBTOT", "POBFEM"]]

El promedio de poblacion femenina es de  2016894.8125

                 NOM_ENT   POBTOT   POBFEM
0         Aguascalientes  1425607   728924
1        Baja California  3769020  1868431
2    Baja California Sur   798447   392568
3               Campeche   928363   471424
4   Coahuila de Zaragoza  3146771  1583102
5                 Colima   731391   370769
7              Chihuahua  3741869  1888047
9                Durango  1832650   927784
11              Guerrero  3540685  1840073
12               Hidalgo  3082841  1601462
16               Morelos  1971520  1020673
17               Nayarit  1235456   623178
19                Oaxaca  4132148  2157305
21             Querétaro  2368467  1211647
22          Quintana Roo  1857985   921206
23       San Luis Potosí  2822255  1449804
24               Sinaloa  3026943  1532128
25                Sonora  2944840  1472643
26               Tabasco  2402598  1228927
27            Tamaulipas  3527735  1791595
28              Tlaxcala  1342977   693083
30               Yucatán  2320898  1180619
31             Zacatecas  1622138   831080

### Ejercicio tarea 3


Parte 1 - Que estados tienen poblacion total entre 700,000 y 1.5 millones?

In [67]:
df.loc[(df["POBTOT"] >= 700000) & (df["POBTOT"] <= 1500000), ["NOM_ENT", "POBTOT"]]

                NOM_ENT   POBTOT
0        Aguascalientes  1425607
2   Baja California Sur   798447
3              Campeche   928363
5                Colima   731391
17              Nayarit  1235456
28             Tlaxcala  1342977

Parte 2 - cuales de ellos tienen poblacion femenina mayor a la masculina?

In [68]:
df.loc[(df["POBFEM"] > df["POBMAS"]), ["NOM_ENT", "POBFEM", "POBMAS"]]

                            NOM_ENT   POBFEM   POBMAS
0                    Aguascalientes   728924   696683
3                          Campeche   471424   456939
4              Coahuila de Zaragoza  1583102  1563669
5                            Colima   370769   360622
6                           Chiapas  2837881  2705947
7                         Chihuahua  1888047  1853822
8                  Ciudad de México  4805017  4404927
9                           Durango   927784   904866
10                       Guanajuato  3170480  2996454
11                         Guerrero  1840073  1700612
12                          Hidalgo  1601462  1481379
13                          Jalisco  4249696  4098455
14                           México  8741123  8251295
15              Michoacán de Ocampo  2442505  2306341
16                          Morelos  1020673   950847
17                          Nayarit   623178   612278
18                       Nuevo León  2893492  2890950
19                           Oaxaca  2157305  1974843
20                           Puebla  3423163  3160115
21                        Querétaro  1211647  1156820
23                  San Luis Potosí  1449804  1372451
24                          Sinaloa  1532128  1494815
25                           Sonora  1472643  1472197
26                          Tabasco  1228927  1173671
27                       Tamaulipas  1791595  1736140
28                         Tlaxcala   693083   649894
29  Veracruz de Ignacio de la Llave  4190805  3871774
30                          Yucatán  1180619  1140279
31                        Zacatecas   831080   791058

In [69]:
type(df["POBTOT"])

pandas.core.series.Series

### Investigaciones de conceptos

- Investigar framework medallion
- LLM
- Comparativa: Azure, AWS, GCP para datos
- Dashboards
- SQL

## What is a dashboard? - Finish

---

A dashboard is a way of displaying various types of visual data in one place. Usually, a dashboard is intended to convey different, but related information in an easy to read way. The most common use case for dashboards are includes  key performance indicators (KPIs) and other important business metrics that decision makers use in theyr day to day activities.

The concept of dashboards may be confused the concept of data visualization. Dashboards are a neat way of visualizing data, they focus on being appealing to the eye, being interactive and connecting several data bases. That is, dashboards are one aspect of the more ample domain of data visualization.

### Common data vizualitaion softwares

There are two main data vizualitaion softwares that are used in the market:

- Tableou
- PowerBi

Both give many tools to develop interactive and attarctive dashboards, facilitating shareability and customization. Both take most part of the market, altough other less popular softwares/libraries exists. An example is Plotly Dash, a python library that allows for the development of dashboards using html and css.

## What is an LLM? - Finish

The acronym 'LMM' stand for Large Language Model. The concept become increasingly popular (with the general population) with the realease of chatgpt by OpenIA (leader in the AI industry). This type of models are a category of deep learning models trained on immense amounts of data, making them capable of understanding and generating natural language and other types of content to perform a wide range of tasks. They are built on a type of neural network (a complicated computational model that mimics the way neurons work in the human brain).

This type of models do not really understand the topics they are able to discuss with enough training. Still, they are extremelly powerfull statistical prediction machines whose whole job is to predict the next word in a sequence.

### Pandas Index Objects

---

PENDIENTE - COMPLETAR APUNTES: LO BASICO DE INDEX.OBJECTS

A dataframe is a data type that which has a tabular structure where all
Un dataframe es un tipo de estrutura de dato tabular donde todos los datos de una fila estan relacionados.

## PENDIENTES

---

- terminar de investigar tareas
- terminar apuntes tipos de datos basicos
- extender apuntes de filtros de datos basicos
- extender apuntes de manipulacion de series y DataFrames